### ISSUE TITLE
[FIX] 빵집 상세보기에 네이버 지도 길찾기 URL 추가

### ISSUE THREAD

**Issue by sung-silver** [GEON-PPANG/GEON-PPANG-SERVER#133]
## 🍞 Description

- 1차 릴리즈 기능 변경에 따라 빵집 상세보기에 네이버 지도 길찾기 URL도 response 값에 함께 넘겨주어야 합니다

## 🍞 To-do
- [ ] bakery 엔티티에 네이버 지도 URL 저장할 필드 추가하기
- [ ] 관련 responseDTO 수정하기
- [ ] log 추적되는 문제 해결하기

## 🍞 ETC
- 예상 마감: 8/12 (수)
