### ISSUE TITLE
[FIX] Bakery 엔티티에 instagram url 필드 추가

### ISSUE THREAD

**Issue by sung-silver** [GEON-PPANG/GEON-PPANG-SERVER#136]
## 🍞 Description

- 추후 추가될 기능으로 빵집 상세보기 페이지에 홈페이지 외 인스타그램 url도 추가된다고하여 Bakery 엔티티를 수정하고자 합니다

## 🍞 To-do
- [ ] bakery 엔티티에 instagramUrl 추가
- [ ] 기존 homepage 필드명을 homepageUrl로 변경
- [ ] url에 해당하는 필드 h2/mysql 데이터베이스 생성 스크립트에서 크기를 2500으로 수정

## 🍞 ETC
- 예상 마감: 8/13 (일)
