### ISSUE TITLE
[FIX] NutrientType, BreadType 엔티티를 다대다 관계로 변경해라

### ISSUE THREAD

**Issue by sung-silver** [GEON-PPANG/GEON-PPANG-SERVER#255]
## 🍞 Description

- Category 엔티티와 동일하게 NutrientType과 BreadType 엔티티도 다대다 관계로 변경합니다

## 🍞 To-do
- [ ] NutrientType 엔티티 수정
- [ ] BreadType 엔티티 수정
- [ ] schema.sql 수정
- [ ] data.sql 수정
- [ ] 파이썬 db 적재 코드 수정
- [ ] DB insert 전용 계정 생성

## 🍞 ETC
- 마감: 승하언니와 코딩카페에서..
