### ISSUE TITLE
[FIX] API 명세서와 비교하여 변수명 수정

### ISSUE THREAD

**Issue by sung-silver** [GEON-PPANG/GEON-PPANG-SERVER#42]
## 🍞 Description

- api 명세서와 확인 후 responseDto의 필드명 통일을 진행해야 합니다

## 🍞 To-do
- [x] 건빵집 리스트 조회 확인
- [x] 건빵집 상세조회 확인
- [x] 건빵집 작성된 리뷰 조회 확인
- [x] 건빵집 리뷰 작성 확인
- [x] 마이페이지 회원정보 조회 확인
- [x] 리뷰 모아보기 (마이페이지) 확인
- [x] 리뷰 상세보기 (리뷰 모아보기) 확인

## 🍞 ETC
- 예상 마감: 7/13 (목) -> 7/14(금) 넘어가는 새벽
