### ISSUE TITLE
[FIX] 수정된 반영사항에 따라 BaseBakeryEntity 수정 및 관련 api에서 사용되는 ResponseDto 내용 수정

### ISSUE THREAD

**Issue by sung-silver** [GEON-PPANG/GEON-PPANG-SERVER#71]
## 🍞 Description

- 뷰 수정으로 인하여 수정되는 Bakery 관련 responseDto를 수정한다

## 🍞 To-do
- [x] BEST 건빵집 카드관련 api 수정
- [x] BEST 리뷰 카드 관련 api 수정
- [x] 건빵집 이름으로 검색하는 api 수정
- [x] 건빵집 리스트 관련 api 수정
- [x] 건빵집 상세보기 정보 추가
- [x] 북마크한 건빵집 조회 api 수정

## 🍞 ETC
- 예상 마감: 7/17 (월)
