### ISSUE TITLE
[FIX] 수정된 api 명세서에 맞게 controller를 수정

### ISSUE THREAD

**Issue by sung-silver** [GEON-PPANG/GEON-PPANG-SERVER#81]
## 🍞 Description

- api 명세서 url 수정으로 인하여 controller 로직을 전반적으로 수정해야 합니다

## 🍞 To-do
- [x] {base_url}/auth/signup
- [x] {base_url}/auth/login
- [x] {base_url}/validation/nickname
- [x] {base_url}/validation/email
- [x] {base_url}/member/types
- [x] {base_url}/search/bakeries?bakeryName=
- [x] {base_url}/best/bakeries
- [x] {base_url}best/reviews
- [x] {base_url}/bakeries?sort=default&isHard=ture&isDessert=false&isBrunch
- [x] {base_url}/bakeries/{bakeryId}
- [x] {base_url}/reviews/{bakeryId}
- [x] {base_url}/bookMarks/{bakeryId}
- [x] {base_url}/reviews/{bakeryId}
- [x] {base_url}/member
- [x] {base_url}/member/reviews
- [x] {base_url}/reviews/{reviewId}
- [x] {base_url}/member/bookMarks
- [x]  {base_url}/member/types
