### ISSUE TITLE
[FIX] 7/18 코드 리뷰 반영

### ISSUE THREAD

**Issue by sung-silver** [GEON-PPANG/GEON-PPANG-SERVER#91]
## 🍞 Description

- 7/18에 받은 코드리뷰를 반영합니다
  - 건빵집에 작성된 리뷰 조회시 Percent를 구하는 로직을 함수로 분리합니다
  - bakery 테이블에서 count를 증가시키는 로직은 saveAndFlush를 사용합니다
  - recommendKeywordCount와 관련된 키워드를 enum으로 관리합니다
## 🍞 To-do
- [ ] 건빵집에 작성된 리뷰 조회시 Percent를 구하는 로직을 함수로 분리
- [ ] bakery 테이블에서 count를 증가시키는 로직은 saveAndFlush를 사용
- [ ] recommendKeywordCount와 관련된 키워드를 enum으로 관리
